name: Release

on:
  workflow_dispatch:
    inputs:
      rel:
        description: "rel"
        required: true
        default: 1

jobs:
  create_arch_package:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Update aur PKGBUILD
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm openssh git base-devel

          useradd -m -G wheel runner
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R runner:runner .

          su runner -c '
              # Used by PKGBUILD internally 
              set -e
              VERSION=${GITHUB_REF#refs/tags/v}
              export VERSION

              mkdir -p ~/.ssh
              echo "${{ secrets.AUR_SSH_KEY }}" > ~/.ssh/aur
              chmod 600 ~/.ssh/aur
              echo "Host aur.archlinux.org" >> ~/.ssh/config
              echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
              echo "  User aur" >> ~/.ssh/config
              ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts

              git clone ssh://aur@aur.archlinux.org/please-cli.git aur

              cp PKGBUILD aur/
              cd aur/
              sed -i -e "s/^pkgrel=.*/pkgrel=${{ github.event.inputs.rel }}/" PKGBUILD
              makepkg --printsrcinfo > .SRCINFO
              makepkg

              git config user.name "info@tngtech.com"
              git config user.email "TNG Technology Consulting"
              git add PKGBUILD .SRCINFO
              git commit -m "release $VERSION"
              git push origin master
          '

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: please-cli arch package ${{ github.ref }}
          path: please-cli/please-cli-*.pkg.tar
